-- Insert sample data for Student Admit Card Management
INSERT INTO student_admit_cards (
  student_id,
  student_name,
  fathers_name,
  mothers_name,
  course_name,
  roll_number,
  exam_date,
  exam_center_code,
  exam_center_address,
  exam_start_time,
  reporting_time,
  gate_closing_time,
  exam_duration,
  batch,
  pwd_status,
  student_photo_url
) VALUES 
(
  'ST001',
  'Rajesh Kumar',
  'Suresh Kumar',
  'Sunita Devi',
  'Computer Applications',
  'CA001',
  '2024-03-15',
  'EC001',
  'Government Polytechnic, Sector 15, Chandigarh',
  '10:00 AM',
  '9:00 AM',
  '9:30 AM',
  '3 Hours',
  'Batch A',
  'No',
  'https://example.com/photos/rajesh.jpg'
),
(
  'ST002',
  'Priya Sharma',
  'Ramesh Sharma',
  'Meera Sharma',
  'Digital Marketing',
  'DM002',
  '2024-03-16',
  'EC002',
  'Technical Training Center, Sector 22, Chandigarh',
  '2:00 PM',
  '1:00 PM',
  '1:30 PM',
  '2 Hours',
  'Batch B',
  'No',
  'https://example.com/photos/priya.jpg'
),
(
  'ST003',
  'Amit Singh',
  'Harpal Singh',
  'Kulwinder Kaur',
  'Web Development',
  'WD003',
  '2024-03-17',
  'EC001',
  'Government Polytechnic, Sector 15, Chandigarh',
  '10:00 AM',
  '9:00 AM',
  '9:30 AM',
  '4 Hours',
  'Batch A',
  'No',
  'https://example.com/photos/amit.jpg'
),
(
  'ST004',
  'Sneha Gupta',
  'Rakesh Gupta',
  'Anita Gupta',
  'Data Entry Operations',
  'DE004',
  '2024-03-18',
  'EC003',
  'Industrial Training Institute, Phase 7, Mohali',
  '9:00 AM',
  '8:00 AM',
  '8:30 AM',
  '2.5 Hours',
  'Batch C',
  'Yes',
  'https://example.com/photos/sneha.jpg'
),
(
  'ST005',
  'Vikash Yadav',
  'Sunil Yadav',
  'Pooja Yadav',
  'Tally with GST',
  'TG005',
  '2024-03-19',
  'EC002',
  'Technical Training Center, Sector 22, Chandigarh',
  '11:00 AM',
  '10:00 AM',
  '10:30 AM',
  '3 Hours',
  'Batch B',
  'No',
  'https://example.com/photos/vikash.jpg'
),
(
  'ST006',
  'Neha Patel',
  'Mahesh Patel',
  'Kavita Patel',
  'Computer Applications',
  'CA006',
  '2024-03-20',
  'EC001',
  'Government Polytechnic, Sector 15, Chandigarh',
  '10:00 AM',
  '9:00 AM',
  '9:30 AM',
  '3 Hours',
  'Batch A',
  'No',
  'https://example.com/photos/neha.jpg'
),
(
  'ST007',
  'Rohit Verma',
  'Dinesh Verma',
  'Sushma Verma',
  'Mobile Repairing',
  'MR007',
  '2024-03-21',
  'EC003',
  'Industrial Training Institute, Phase 7, Mohali',
  '2:00 PM',
  '1:00 PM',
  '1:30 PM',
  '2 Hours',
  'Batch C',
  'No',
  'https://example.com/photos/rohit.jpg'
),
(
  'ST008',
  'Kavya Joshi',
  'Rajendra Joshi',
  'Urmila Joshi',
  'English Communication',
  'EC008',
  '2024-03-22',
  'EC002',
  'Technical Training Center, Sector 22, Chandigarh',
  '3:00 PM',
  '2:00 PM',
  '2:30 PM',
  '1.5 Hours',
  'Batch B',
  'No',
  'https://example.com/photos/kavya.jpg'
),
(
  'ST009',
  'Manish Agarwal',
  'Vinod Agarwal',
  'Rekha Agarwal',
  'AutoCAD',
  'AC009',
  '2024-03-23',
  'EC001',
  'Government Polytechnic, Sector 15, Chandigarh',
  '9:30 AM',
  '8:30 AM',
  '9:00 AM',
  '4 Hours',
  'Batch A',
  'No',
  'https://example.com/photos/manish.jpg'
),
(
  'ST010',
  'Pooja Kumari',
  'Ashok Kumar',
  'Sunita Kumari',
  'Beauty & Wellness',
  'BW010',
  '2024-03-24',
  'EC003',
  'Industrial Training Institute, Phase 7, Mohali',
  '10:30 AM',
  '9:30 AM',
  '10:00 AM',
  '3.5 Hours',
  'Batch C',
  'No',
  'https://example.com/photos/pooja.jpg'
);